site_name: Siddhi-Execution-Unique
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Execution Unique: index.md
- API Docs:
  - 4.0.25: api/4.0.25.md
  - 4.0.24: api/4.0.24.md
  - 4.0.23: api/4.0.23.md
  - 4.0.22: api/4.0.22.md
  - 4.0.21: api/4.0.21.md
  - 4.0.20: api/4.0.20.md
  - 4.0.19: api/4.0.19.md
  - 4.0.18: api/4.0.18.md
  - 4.0.17: api/4.0.17.md
  - 4.0.16: api/4.0.16.md
  - 4.0.15: api/4.0.15.md
  - 4.0.14: api/4.0.14.md
  - 4.0.13: api/4.0.13.md
  - 4.0.12: api/4.0.12.md
  - 4.0.10: api/4.0.10.md
  - 4.0.9: api/4.0.9.md
  - 4.0.8: api/4.0.8.md
  - 4.0.7: api/4.0.7.md
  - latest: api/latest.md
- License: license.md
theme: material
